# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pose.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\npose.proto\x12\rsim_data_flow\"8\n\nQuaternion\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x12\t\n\x01w\x18\x04 \x01(\x01\"*\n\x07Vector3\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\"s\n\x04Pose\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12(\n\x08position\x18\x02 \x01(\x0b\x32\x16.sim_data_flow.Vector3\x12.\n\x0borientation\x18\x03 \x01(\x0b\x32\x19.sim_data_flow.Quaternionb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pose_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _QUATERNION._serialized_start=29
  _QUATERNION._serialized_end=85
  _VECTOR3._serialized_start=87
  _VECTOR3._serialized_end=129
  _POSE._serialized_start=131
  _POSE._serialized_end=246
# @@protoc_insertion_point(module_scope)
