# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transfer.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0etransfer.proto\x12\rsim_data_flow\"8\n\nQuaternion\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x12\t\n\x01w\x18\x04 \x01(\x01\"*\n\x07Vector3\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\"s\n\x04Pose\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12(\n\x08position\x18\x02 \x01(\x0b\x32\x16.sim_data_flow.Vector3\x12.\n\x0borientation\x18\x03 \x01(\x0b\x32\x19.sim_data_flow.Quaternion\"\x85\x01\n\x08Transfer\x12\x0e\n\x06nodeId\x18\x01 \x01(\x05\x12+\n\x0btranslation\x18\x02 \x01(\x0b\x32\x16.sim_data_flow.Vector3\x12+\n\x08rotation\x18\x03 \x01(\x0b\x32\x19.sim_data_flow.Quaternion\x12\x0f\n\x07\x64oorTag\x18\x04 \x01(\x08\"g\n\tMTransfer\x12\'\n\nrobot_pose\x18\x01 \x01(\x0b\x32\x13.sim_data_flow.Pose\x12$\n\x03map\x18\x02 \x03(\x0b\x32\x17.sim_data_flow.Transfer\x12\x0b\n\x03seq\x18\x03 \x01(\x04\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transfer_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _QUATERNION._serialized_start=33
  _QUATERNION._serialized_end=89
  _VECTOR3._serialized_start=91
  _VECTOR3._serialized_end=133
  _POSE._serialized_start=135
  _POSE._serialized_end=250
  _TRANSFER._serialized_start=253
  _TRANSFER._serialized_end=386
  _MTRANSFER._serialized_start=388
  _MTRANSFER._serialized_end=491
# @@protoc_insertion_point(module_scope)
